services:
  app:
    image: gitea/gitea:1.22.2
    container_name: gitea
    environment:
      USER_UID: "${USER_UID}"
      USER_GID: "${USER_GID}"
      GITEA__database__DB_TYPE: "${GITEA__database__DB_TYPE}"
      GITEA__database__HOST: "${GITEA__database__HOST}"
      GITEA__database__NAME: "${GITEA__database__NAME}"
      GITEA__database__USER: "${GITEA__database__USER}"
      GITEA__database__PASSWD: "${GITEA__database__PASSWD}"
      GITEA__service__DISABLE_REGISTRATION: "${GITEA__service__DISABLE_REGISTRATION}"
    restart: always
    networks:
      - gitea
      - proxy
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gitea-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
     - gitea
    volumes:
      - ./mysql:/var/lib/mysql

  runner:
    image: gitea/act_runner:nightly
    container_name: gitea-runner
    restart: always
    environment:
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "${GITEA_RUNNER_NAME}"
      GITEA_RUNNER_LABELS: "${GITEA_RUNNER_LABELS}"
    volumes:
      - ./data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

networks:
  gitea:
    external: false
  proxy:
    external: true